### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by nonZero** [myExperiment/myexperiment-rdf#1]
Hi!

Does this project (and especially the "How To SPARQL" pages) are under the same license as described in the main MyExperiment repoistory (<https://github.com/myExperiment/myExperiment/blob/master/LICENSE>) ?

Thanks!

**Comment by fbacall** [comment]
Hi, this code was written by @drn05r during his PhD - perhaps he could comment on the license?

**Comment by drn05r** [comment]
As far as I am concerned it should be considered to be under the same license as myExperiment.  As it is so closely tied to myExperiment, at the time, I do not think I gave it much consideration, as I would have thought it was unlikely anyone would want to make use of it without already using MyExperiment's code and being bound by that license.

@fbacall feel free to add the MyExperiment license to this Git repository.

**Comment by fbacall** [comment]
Great, thanks David!
